from PyQt5 import QtCore, QtGui, QtWidgets
#self.dateTimeEdit.setDisplayFormat("dd/MM/yyyy hh:mm")
#self.pushButton.clicked.connect(self.storeAppointment)
from PyQt5.QtGui import QStandardItemModel, QStandardItem


class Ui_Dialog(object):
    def getDateTime(self):
        dt=self.dateTimeEdit.dateTime()
        dt_string=dt.toString(self.dateTimeEdit.displayFormat())
        return dt_string
    def storeAppointment(self):
        subjecText=self.lineEdit.text()
        appointmentDetails=self.textEdit.toPlainText()
        deets=str(appointmentDetails)
        datetime=self.getDateTime()
        facultyRequested=self.comboBox.currentText()
        requestedFaculuty=str(facultyRequested)
        appointmentFile=open(subjecText+".txt", 'w+')
        appointmentFile.write(datetime+'\n')
        appointmentFile.write(requestedFaculuty+'\n')
        appointmentFile.write('\n'+deets)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(976, 565)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 541, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.appform = QtWidgets.QLabel(self.frame)
        self.appform.setGeometry(QtCore.QRect(20, 30, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.appform.setFont(font)
        self.appform.setObjectName("appform")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 90, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 120, 311, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 220, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(20, 320, 491, 91))
        self.textEdit.setObjectName("textEdit")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 250, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit.setDisplayFormat("MM/dd/yyyy hh:mm")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 440, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.storeAppointment)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 440, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 180, 311, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(580, 20, 371, 521))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 331, 121))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 119))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 0, 331, 121))
        self.listView.setObjectName("listView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.appform_2 = QtWidgets.QLabel(self.frame_2)
        self.appform_2.setGeometry(QtCore.QRect(20, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.appform_2.setFont(font)
        self.appform_2.setObjectName("appform_2")
        self.appform_3 = QtWidgets.QLabel(self.frame_2)
        self.appform_3.setGeometry(QtCore.QRect(20, 250, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.appform_3.setFont(font)
        self.appform_3.setObjectName("appform_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 300, 331, 121))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 329, 119))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.appform.setText(_translate("Dialog", "Application Form"))
        self.label.setText(_translate("Dialog", "Appointment Subject"))
        self.label_2.setText(_translate("Dialog", "Schedule"))
        self.label_3.setText(_translate("Dialog", "Appointment Details"))
        self.pushButton.setText(_translate("Dialog", "Set Appointment"))
        self.pushButton_2.setText(_translate("Dialog", "Get Priority Number"))
        self.label_4.setText(_translate("Dialog", "Appointment Subject"))
        self.comboBox.setItemText(0, _translate("Dialog", "Faculty "))
        self.comboBox.setItemText(1, _translate("Dialog", "Teacher 1"))
        self.comboBox.setItemText(2, _translate("Dialog", "Teacher 2"))
        self.comboBox.setItemText(3, _translate("Dialog", "Teacher 3"))
        self.appform_2.setText(_translate("Dialog", "View Appointments"))
        self.appform_3.setText(_translate("Dialog", "Appointment History"))