from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import os
import pathlib

from Rappoint import Ui_Dialog as Laes

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        def browse():
            filename = QFileDialog.getOpenFileName(Dialog, 'Open file', '', "Text files (*.txt)")
            if filename[0]:
                f=open(filename[0], 'r')
                with f:
                    fline = f.readline()
                    data = f.read()
                    self.textBrowser.setText(data)
                    self.textBrowser_2.setText(fline)
                    g=open("appHistory.txt",'a')
                    g.write(fline+"\n")
            print("Accepted Appointment")
        def cancelAppointment():
            appCanceled = QFileDialog.getOpenFileName(Dialog, 'Open file', '', "Text files (*.txt)")
            if appCanceled[0]:
                f=open(appCanceled[0], 'r')
                with f:
                    fileName=f.readline().strip()
                path=pathlib.Path(fileName+'.txt')
                path.unlink()
                print("Appointment Canceled and Deleted")
        Dialog.setObjectName("Dialog")
        Dialog.resize(1072, 563)
        self.appointmentsFrame = QtWidgets.QFrame(Dialog)
        self.appointmentsFrame.setGeometry(QtCore.QRect(10, 10, 611, 541))
        self.appointmentsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appointmentsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appointmentsFrame.setObjectName("appointmentsFrame")
        self.appform_8 = QtWidgets.QLabel(self.appointmentsFrame)
        self.appform_8.setGeometry(QtCore.QRect(20, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.appform_8.setFont(font)
        self.appform_8.setObjectName("appform_8")
        self.appform_9 = QtWidgets.QLabel(self.appointmentsFrame)
        self.appform_9.setGeometry(QtCore.QRect(20, 300, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.appform_9.setFont(font)
        self.appform_9.setObjectName("appform_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.appointmentsFrame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 100, 571, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.appointmentsFrame)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 350, 571, 171))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.settingsFrame = QtWidgets.QFrame(Dialog)
        self.settingsFrame.setGeometry(QtCore.QRect(650, 10, 411, 541))
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.availabilityGroupBox = QtWidgets.QGroupBox(self.settingsFrame)
        self.availabilityGroupBox.setGeometry(QtCore.QRect(40, 130, 331, 121))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.availabilityGroupBox.setFont(font)
        self.availabilityGroupBox.setObjectName("availabilityGroupBox")
        self.radioButton = QtWidgets.QRadioButton(self.availabilityGroupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 40, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.availabilityGroupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 70, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.clockFrame = QtWidgets.QFrame(self.settingsFrame)
        self.clockFrame.setGeometry(QtCore.QRect(10, 10, 391, 111))
        self.clockFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clockFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clockFrame.setObjectName("clockFrame")
        self.label = QtWidgets.QLabel(self.clockFrame)
        self.label.setGeometry(QtCore.QRect(80, 30, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.settingsFrame)
        self.pushButton.setGeometry(QtCore.QRect(40, 270, 321, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(browse)
        self.pushButton_2 = QtWidgets.QPushButton(self.settingsFrame)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 340, 321, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.settingsFrame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 410, 321, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(cancelAppointment)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.appform_8.setText(_translate("Dialog", "View Appointments"))
        self.appform_9.setText(_translate("Dialog", "Appointment History"))
        self.availabilityGroupBox.setTitle(_translate("Dialog", "Availability"))
        self.radioButton.setText(_translate("Dialog", "Taking Appointments"))
        self.radioButton_2.setText(_translate("Dialog", "Not Taking Appointments"))
        self.label.setText(_translate("Dialog", "CLOCK HERE EVENTUALLY"))
        self.pushButton.setText(_translate("Dialog", "Select Appointment to Accept"))
        self.pushButton_2.setText(_translate("Dialog", "Next Appointment"))
        self.pushButton_3.setText(_translate("Dialog", "Select Appointment to Cancel"))