# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QMessageBox


class Ui_registrationWindow2(object):
    def createRegisterFunction(self):
            id = self.inputID.text()
            first = self.inputFirstName.text()
            middle = self.inputMI.text()
            last = self.inputLastName.text()
            course = self.inputCourse.text()
            year = self.inputYear.text()
            email2 = self.inputEmail2.text()
            contact = self.inputContact.text()
            if self.inputPassword2.text() == self.inputConfirmation.text():
                    inputPassword = self.inputPassword2.text()

                    print('Account Created Successfully!')
                    print('ID: ', id)
                    print('Name: ', first, middle, last)
                    print('Course and Year: ', course, year)
                    print('Contact Number: ', contact)
                    print('Email: ', email2)
                    print('Password: ', inputPassword)

                    msg = QMessageBox()
                    msg.setWindowTitle('Registration Confirmation')
                    msg.setText('You have successfully created your account!')
                    x = msg.exec_()

                    accountFile = open(id + ".txt", 'w+')
                    accountFile.write("ID: "+id+'\n')
                    accountFile.write("Name: " + first + ' ' + middle + ' ' + last + '\n')
                    accountFile.write("Course and Year: " + course + ' ' + year + '\n')
                    accountFile.write("Contact Number: " + contact + '\n')
                    accountFile.write("Email: " + email2 + '\n')
                    accountFile.write("Password: " + inputPassword)

            else:
                    print('Password mismatch')
                    msg = QMessageBox()
                    msg.setWindowTitle('Registration Confirmation')
                    msg.setText('Incorrect Password')
                    x = msg.exec_()



    def openLoginWindow(self):# ga error if iimport ang loginPage
            self.windowlogin2 = QtWidgets.QMainWindow()
            self.ui = Ui_loginWindow2()
            self.ui.setup(self.windowlogin2)
            # registrationWindow.hide()
            self.windowlogin2.show()


    def setupUi(self, registrationWindow2):
        registrationWindow2.setObjectName("registrationWindow2")
        registrationWindow2.resize(1020, 700)
        registrationWindow2.setStyleSheet("background-color: rgb(21, 31, 41);\n"
"font: 12pt \"Nunito\";")
        self.loginFrame = QtWidgets.QFrame(registrationWindow2)
        self.loginFrame.setGeometry(QtCore.QRect(0, 110, 1051, 601))
        self.loginFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.registrationFormLabel = QtWidgets.QLabel(self.loginFrame)
        self.registrationFormLabel.setGeometry(QtCore.QRect(400, 20, 291, 51))
        self.registrationFormLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.registrationFormLabel.setStyleSheet("font: 36pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);")
        self.registrationFormLabel.setObjectName("registrationFormLabel")
        self.idLabel = QtWidgets.QLabel(self.loginFrame)
        self.idLabel.setGeometry(QtCore.QRect(190, 100, 101, 16))
        self.idLabel.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(21, 31, 41);")
        self.idLabel.setObjectName("idLabel")
        self.nameLabel = QtWidgets.QLabel(self.loginFrame)
        self.nameLabel.setGeometry(QtCore.QRect(190, 170, 111, 16))
        self.nameLabel.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.nameLabel.setObjectName("nameLabel")
        self.inputFirstName = QtWidgets.QLineEdit(self.loginFrame)
        self.inputFirstName.setGeometry(QtCore.QRect(190, 190, 301, 31))
        self.inputFirstName.setObjectName("inputFirstName")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.loginFrame)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 910, 281, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.inputID = QtWidgets.QLineEdit(self.loginFrame)
        self.inputID.setGeometry(QtCore.QRect(190, 120, 301, 31))
        self.inputID.setObjectName("inputID")
        self.inputMI = QtWidgets.QLineEdit(self.loginFrame)
        self.inputMI.setGeometry(QtCore.QRect(500, 190, 101, 31))
        self.inputMI.setObjectName("inputMI")
        self.inputLastName = QtWidgets.QLineEdit(self.loginFrame)
        self.inputLastName.setGeometry(QtCore.QRect(610, 190, 261, 31))
        self.inputLastName.setObjectName("inputLastName")
        self.inputCourse = QtWidgets.QLineEdit(self.loginFrame)
        self.inputCourse.setGeometry(QtCore.QRect(190, 260, 571, 31))
        self.inputCourse.setText("")
        self.inputCourse.setObjectName("inputCourse")
        self.courseYearLabel = QtWidgets.QLabel(self.loginFrame)
        self.courseYearLabel.setGeometry(QtCore.QRect(190, 240, 151, 16))
        self.courseYearLabel.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.courseYearLabel.setObjectName("courseYearLabel")
        self.inputYear = QtWidgets.QLineEdit(self.loginFrame)
        self.inputYear.setGeometry(QtCore.QRect(770, 260, 101, 31))
        self.inputYear.setText("")
        self.inputYear.setObjectName("inputYear")
        self.inputEmail2 = QtWidgets.QLineEdit(self.loginFrame)
        self.inputEmail2.setGeometry(QtCore.QRect(190, 330, 681, 31))
        self.inputEmail2.setText("")
        self.inputEmail2.setObjectName("inputEmail2")
        self.inputContact = QtWidgets.QLineEdit(self.loginFrame)
        self.inputContact.setGeometry(QtCore.QRect(190, 470, 331, 31))
        self.inputContact.setText("")
        self.inputContact.setObjectName("inputContact")
        self.emailLabelRegistration = QtWidgets.QLabel(self.loginFrame)
        self.emailLabelRegistration.setGeometry(QtCore.QRect(190, 310, 151, 16))
        self.emailLabelRegistration.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.emailLabelRegistration.setObjectName("emailLabelRegistration")
        self.contactLabel = QtWidgets.QLabel(self.loginFrame)
        self.contactLabel.setGeometry(QtCore.QRect(190, 450, 151, 16))
        self.contactLabel.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.contactLabel.setObjectName("contactLabel")
        self.passwordLabelRegistration = QtWidgets.QLabel(self.loginFrame)
        self.passwordLabelRegistration.setGeometry(QtCore.QRect(190, 380, 151, 16))
        self.passwordLabelRegistration.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.passwordLabelRegistration.setObjectName("passwordLabelRegistration")
        self.inputPassword2 = QtWidgets.QLineEdit(self.loginFrame)
        self.inputPassword2.setGeometry(QtCore.QRect(190, 400, 331, 31))
        self.inputPassword2.setText("")


        self.inputPassword2.setObjectName("inputPassword2")
        self.inputPassword2.setEchoMode(QtWidgets.QLineEdit.Password)


        self.inputConfirmation = QtWidgets.QLineEdit(self.loginFrame)
        self.inputConfirmation.setGeometry(QtCore.QRect(530, 400, 341, 31))
        self.inputConfirmation.setText("")


        self.inputConfirmation.setObjectName("inputConfirmation")
        self.inputConfirmation.setEchoMode(QtWidgets.QLineEdit.Password)


        self.confirmLabel = QtWidgets.QLabel(self.loginFrame)
        self.confirmLabel.setGeometry(QtCore.QRect(530, 380, 161, 16))
        self.confirmLabel.setStyleSheet("font: 14pt bold \"Poppins\";\n"
"color: rgb(21, 31, 41);")
        self.confirmLabel.setObjectName("confirmLabel")
        self.registerButton2 = QtWidgets.QPushButton(self.loginFrame)
        self.registerButton2.setGeometry(QtCore.QRect(750, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.registerButton2.setFont(font)
        self.registerButton2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerButton2.setStyleSheet("font: 75 10pt \"Montserrat\";\n"
"color: rgb(230, 230, 230);\n"
"background-color: rgb(21, 31, 41);")


        self.registerButton2.setObjectName("registerButton2")
        self.registerButton2.clicked.connect(self.createRegisterFunction)  # open popup confirmation


        self.headingFrame = QtWidgets.QFrame(registrationWindow2)
        self.headingFrame.setGeometry(QtCore.QRect(0, 0, 1051, 101))
        self.headingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.headingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.headingFrame.setObjectName("headingFrame")
        self.priorityNumberRegistration = QtWidgets.QLabel(self.headingFrame)
        self.priorityNumberRegistration.setGeometry(QtCore.QRect(940, 30, 71, 51))
        self.priorityNumberRegistration.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.priorityNumberRegistration.setStyleSheet("font: 36pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);\n"
"background-color: rgb(255, 255, 255);")
        self.priorityNumberRegistration.setObjectName("priorityNumberRegistration")
        self.nowServingFrame = QtWidgets.QFrame(self.headingFrame)
        self.nowServingFrame.setGeometry(QtCore.QRect(830, 20, 191, 61))
        self.nowServingFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nowServingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nowServingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nowServingFrame.setObjectName("nowServingFrame")
        self.nowServingRegistration = QtWidgets.QLabel(self.nowServingFrame)
        self.nowServingRegistration.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.nowServingRegistration.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nowServingRegistration.setStyleSheet("font: 17pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);\n"
"background-color: rgb(255, 255, 255);")
        self.nowServingRegistration.setObjectName("nowServingRegistration")
        self.logoRegistration = QtWidgets.QLabel(self.headingFrame)
        self.logoRegistration.setGeometry(QtCore.QRect(760, 20, 71, 61))
        self.logoRegistration.setText("")
        self.logoRegistration.setPixmap(QtGui.QPixmap("upper.png"))
        self.logoRegistration.setObjectName("logoRegistration")
        self.nowServingFrame.raise_()
        self.priorityNumberRegistration.raise_()
        self.logoRegistration.raise_()

        self.retranslateUi(registrationWindow2)
        QtCore.QMetaObject.connectSlotsByName(registrationWindow2)

    def retranslateUi(self, registrationWindow2):
        _translate = QtCore.QCoreApplication.translate
        registrationWindow2.setWindowTitle(_translate("registrationWindow2", "Dialog"))
        self.registrationFormLabel.setText(_translate("registrationWindow2", "REGISTRATION FORM"))
        self.idLabel.setText(_translate("registrationWindow2", "ID Number"))
        self.nameLabel.setText(_translate("registrationWindow2", "Name"))
        self.inputFirstName.setText(_translate("registrationWindow2", "First"))
        self.inputMI.setText(_translate("registrationWindow2", "MI"))
        self.inputLastName.setText(_translate("registrationWindow2", "Last"))
        self.courseYearLabel.setText(_translate("registrationWindow2", "Course and Year"))
        self.emailLabelRegistration.setText(_translate("registrationWindow2", "Email"))
        self.contactLabel.setText(_translate("registrationWindow2", "Contact Number"))
        self.passwordLabelRegistration.setText(_translate("registrationWindow2", "Password"))
        self.confirmLabel.setText(_translate("registrationWindow2", "Confirm Password"))
        self.registerButton2.setText(_translate("registrationWindow2", "REGISTER"))
        self.priorityNumberRegistration.setText(_translate("registrationWindow2", "000"))
        self.nowServingRegistration.setText(_translate("registrationWindow2", "NOW SERVING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registrationWindow2 = QtWidgets.QDialog()
    ui = Ui_registrationWindow2()
    ui.setupUi(registrationWindow2)
    registrationWindow2.show()
    sys.exit(app.exec_())
