# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherMain2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import pathlib


class Ui_teacherAppointmentWindow2(object):
    def setupUi(self, teacherAppointmentWindow2):
        self.rowCount = 0
        def browse():
            filename = QFileDialog.getOpenFileName(teacherAppointmentWindow2, 'Open file', '', "Text files (*.txt)")
            if filename[0]:
                f=open(filename[0], 'r')
                with f:
                    content=f.readlines()
                    strippedcontent=[x.strip() for x in content]
                    print(strippedcontent)
                    print(self.rowCount)
                    self.appointments.setItem(self.rowCount, 0, QtWidgets.QTableWidgetItem(strippedcontent[3]))
                    self.appointments.setItem(self.rowCount, 1, QtWidgets.QTableWidgetItem(strippedcontent[1]))
                    self.appointments.setItem(self.rowCount, 2, QtWidgets.QTableWidgetItem(strippedcontent[2]))
                    self.appointments.setItem(self.rowCount, 3, QtWidgets.QTableWidgetItem(strippedcontent[0]))
                    self.rowCount += 1
                    print(self.rowCount)
                    #fline = f.readline()
                    #g=open("appHistory.txt",'a')
                    #g.write(fline+"\n")
            print("Accepted Appointment")
        def nextBrowse():
            filename = QFileDialog.getOpenFileName(teacherAppointmentWindow2, 'Open file', '', "Text files (*.txt)")
            if filename[0]:
                f=open(filename[0], 'r')
                with f:
                    content=f.readlines()
                    strippedcontent=[x.strip() for x in content]
                    print(strippedcontent)
                    self.appointments.setItem(0, 0, QtWidgets.QTableWidgetItem(strippedcontent[3]))
                    self.appointments.setItem(0, 1, QtWidgets.QTableWidgetItem(strippedcontent[1]))
                    self.appointments.setItem(0, 2, QtWidgets.QTableWidgetItem(strippedcontent[2]))
                    self.appointments.setItem(0, 3, QtWidgets.QTableWidgetItem(strippedcontent[0]))
                    #fline = f.readline()
                    #g=open("appHistory.txt",'a')
                    #g.write(fline+"\n")
            print("Accepted Appointment")
        def cancelAppointment():
            appCanceled = QFileDialog.getOpenFileName(teacherAppointmentWindow2, 'Open file', '', "Text files (*.txt)")
            if appCanceled[0]:
                f=open(appCanceled[0], 'r')
                with f:
                    fileName=f.readline().strip()
                path=pathlib.Path(fileName+'.txt')
                path.unlink()
                print("Appointment Canceled and Deleted")
        teacherAppointmentWindow2.setObjectName("teacherAppointmentWindow2")
        teacherAppointmentWindow2.resize(1300, 834)
        teacherAppointmentWindow2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Nunito\";")
        #21, 31, 41
        self.appointmentFrame = QtWidgets.QFrame(teacherAppointmentWindow2)
        self.appointmentFrame.setGeometry(QtCore.QRect(0, 0, 1301, 101))
        self.appointmentFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.appointmentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appointmentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appointmentFrame.setObjectName("appointmentFrame")
        self.queuingSystemLabel_4 = QtWidgets.QLabel(teacherAppointmentWindow2)
        self.queuingSystemLabel_4.setGeometry(QtCore.QRect(1200, 20, 71, 51))
        self.queuingSystemLabel_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.queuingSystemLabel_4.setStyleSheet("font: 36pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);\n"
"background-color: rgb(255, 255, 255);")
        self.queuingSystemLabel_4.setObjectName("queuingSystemLabel_4")
        self.nowServingFrame3 = QtWidgets.QFrame(teacherAppointmentWindow2)
        self.nowServingFrame3.setGeometry(QtCore.QRect(1110, 10, 191, 61))
        self.nowServingFrame3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nowServingFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nowServingFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.nowServingFrame3.setObjectName("nowServingFrame3")
        self.nowServingMainStudent = QtWidgets.QLabel(self.nowServingFrame3)
        self.nowServingMainStudent.setGeometry(QtCore.QRect(10, 20, 101, 31))
        self.nowServingMainStudent.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nowServingMainStudent.setStyleSheet("font: 17pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);\n"
"background-color: rgb(255, 255, 255);")
        self.nowServingMainStudent.setObjectName("nowServingMainStudent")
        self.priorityNumberMainStudent = QtWidgets.QLabel(self.nowServingFrame3)
        self.priorityNumberMainStudent.setGeometry(QtCore.QRect(110, 10, 71, 51))
        self.priorityNumberMainStudent.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.priorityNumberMainStudent.setStyleSheet("font: 36pt \"Bebas Neue\";\n"
"color: rgb(21, 31, 41);\n"
"background-color: rgb(255, 255, 255);")
        self.priorityNumberMainStudent.setObjectName("priorityNumberMainStudent")
        self.viewFrame = QtWidgets.QFrame(teacherAppointmentWindow2)
        self.viewFrame.setGeometry(QtCore.QRect(10, 110, 1291, 731))
        self.viewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewFrame.setObjectName("viewFrame")
        self.appointments = QtWidgets.QTableWidget(self.viewFrame)
        self.appointments.setGeometry(QtCore.QRect(70, 160, 551, 521))
        self.appointments.setObjectName("appointments")
        self.appointments.setColumnCount(4)
        self.appointments.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.appointments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointments.setHorizontalHeaderItem(3, item)
        self.appointments.setEditTriggers(QTableWidget.NoEditTriggers)
        self.appointments.setSelectionBehavior(QTableWidget.SelectRows)
        self.appointmentLabel = QtWidgets.QLabel(self.viewFrame)
        self.appointmentLabel.setGeometry(QtCore.QRect(480, 30, 301, 51))
        self.appointmentLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.appointmentLabel.setStyleSheet("font: 46pt \"Bebas Neue\";\n"
"color: rgb(231, 231, 231);")
        self.appointmentLabel.setObjectName("appointmentLabel")
        self.appointmentLabel_2 = QtWidgets.QLabel(self.viewFrame)
        self.appointmentLabel_2.setGeometry(QtCore.QRect(270, 120, 131, 51))
        self.appointmentLabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.appointmentLabel_2.setStyleSheet("font: 20pt \"Bebas Neue\";\n"
"color: rgb(231, 231, 231);")
        self.appointmentLabel_2.setObjectName("appointmentLabel_2")
        self.appointmentHistory = QtWidgets.QTableWidget(self.viewFrame)
        self.appointmentHistory.setGeometry(QtCore.QRect(640, 160, 551, 331))
        self.appointmentHistory.setObjectName("appointmentHistory")
        self.appointmentHistory.setColumnCount(4)
        self.appointmentHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appointmentHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointmentHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointmentHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointmentHistory.setHorizontalHeaderItem(3, item)
        self.historyLabel = QtWidgets.QLabel(self.viewFrame)
        self.historyLabel.setGeometry(QtCore.QRect(850, 120, 71, 51))
        self.historyLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.historyLabel.setStyleSheet("font: 20pt \"Bebas Neue\";\n"
"color: rgb(231, 231, 231);")
        self.historyLabel.setObjectName("historyLabel")
        self.cancelButton_3 = QtWidgets.QPushButton(self.viewFrame)
        self.cancelButton_3.setGeometry(QtCore.QRect(670, 620, 111, 31))
        self.cancelButton_3.clicked.connect(browse)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cancelButton_3.setFont(font)
        self.cancelButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton_3.setStyleSheet("font: 75 10pt \"Montserrat\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(21, 31, 41);\n"
"")
        self.cancelButton_3.setObjectName("cancelButton_3")
        self.frame = QtWidgets.QFrame(self.viewFrame)
        self.frame.setGeometry(QtCore.QRect(639, 510, 551, 171))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 491, 71))
        self.groupBox.setStyleSheet("font: 19pt \"Bebas\";")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(90, 40, 121, 17))
        self.radioButton.setStyleSheet("font: 500 12pt \"Nunito\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(260, 40, 151, 17))
        self.radioButton_2.setStyleSheet("font: 500 12pt \"Nunito\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.cancelButton_4 = QtWidgets.QPushButton(self.frame)
        self.cancelButton_4.setGeometry(QtCore.QRect(160, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cancelButton_4.setFont(font)
        self.cancelButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton_4.setStyleSheet("font: 75 10pt \"Montserrat\";\n"
"background-color: rgb(21, 31, 41);\n"
"color: rgb(255, 255, 255);")
        self.cancelButton_4.setObjectName("cancelButton_4")
        self.cancelButton_2 = QtWidgets.QPushButton(self.frame)
        self.cancelButton_2.clicked.connect(cancelAppointment)
        self.cancelButton_2.setGeometry(QtCore.QRect(290, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cancelButton_2.setFont(font)
        self.cancelButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton_2.setStyleSheet("font: 75 10pt \"Montserrat\";\n"
"background-color: rgb(21, 31, 41);\n"
"color: rgb(255, 255, 255);")
        self.cancelButton_2.setObjectName("cancelButton_2")
        self.logoutButtonTeacher = QtWidgets.QPushButton(self.frame)
        self.logoutButtonTeacher.setGeometry(QtCore.QRect(410, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.logoutButtonTeacher.setFont(font)
        self.logoutButtonTeacher.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutButtonTeacher.setStyleSheet("font: 75 10pt \"Montserrat\";\n"
"background-color: rgb(21, 31, 41);\n"
"color: rgb(255, 255, 255);")
        self.logoutButtonTeacher.setObjectName("logoutButtonTeacher")
        self.frame.raise_()
        self.historyLabel.raise_()
        self.appointmentLabel_2.raise_()
        self.appointments.raise_()
        self.appointmentLabel.raise_()
        self.appointmentHistory.raise_()
        self.cancelButton_3.raise_()
        self.logoMainStudent = QtWidgets.QLabel(teacherAppointmentWindow2)
        self.logoMainStudent.setGeometry(QtCore.QRect(1040, 10, 71, 61))
        self.logoMainStudent.setText("")
        self.logoMainStudent.setPixmap(QtGui.QPixmap("upper.png"))
        self.logoMainStudent.setObjectName("logoMainStudent")
        self.viewFrame.raise_()
        self.appointmentFrame.raise_()
        self.queuingSystemLabel_4.raise_()
        self.nowServingFrame3.raise_()
        self.logoMainStudent.raise_()

        self.retranslateUi(teacherAppointmentWindow2)
        QtCore.QMetaObject.connectSlotsByName(teacherAppointmentWindow2)

    def retranslateUi(self, teacherAppointmentWindow2):
        _translate = QtCore.QCoreApplication.translate
        teacherAppointmentWindow2.setWindowTitle(_translate("teacherAppointmentWindow2", "Dialog"))
        self.queuingSystemLabel_4.setText(_translate("teacherAppointmentWindow2", "000"))
        self.nowServingMainStudent.setText(_translate("teacherAppointmentWindow2", "NOW SERVING"))
        self.priorityNumberMainStudent.setText(_translate("teacherAppointmentWindow2", "000"))
        item = self.appointments.horizontalHeaderItem(0)
        item.setText(_translate("teacherAppointmentWindow2", "Priority #"))
        item = self.appointments.horizontalHeaderItem(1)
        item.setText(_translate("teacherAppointmentWindow2", "Schedule"))
        item = self.appointments.horizontalHeaderItem(2)
        item.setText(_translate("teacherAppointmentWindow2", "Teacher"))
        item = self.appointments.horizontalHeaderItem(3)
        item.setText(_translate("teacherAppointmentWindow2", "Subject"))
        self.appointmentLabel.setText(_translate("teacherAppointmentWindow2", "APPOINTMENTS"))
        self.appointmentLabel_2.setText(_translate("teacherAppointmentWindow2", "Appointments"))
        item = self.appointmentHistory.horizontalHeaderItem(0)
        item.setText(_translate("teacherAppointmentWindow2", "Priority #"))
        item = self.appointmentHistory.horizontalHeaderItem(1)
        item.setText(_translate("teacherAppointmentWindow2", "Schedule"))
        item = self.appointmentHistory.horizontalHeaderItem(2)
        item.setText(_translate("teacherAppointmentWindow2", "Teacher"))
        item = self.appointmentHistory.horizontalHeaderItem(3)
        item.setText(_translate("teacherAppointmentWindow2", "Subject"))
        self.historyLabel.setText(_translate("teacherAppointmentWindow2", "HISTORY"))
        self.cancelButton_3.setText(_translate("teacherAppointmentWindow2", "ACCEPT"))
        self.groupBox.setTitle(_translate("teacherAppointmentWindow2", "AVAILABILITY"))
        self.radioButton.setText(_translate("teacherAppointmentWindow2", "AVAILABLE"))
        self.radioButton_2.setText(_translate("teacherAppointmentWindow2", "NOT AVAILABLE"))
        self.cancelButton_4.setText(_translate("teacherAppointmentWindow2", "NEXT"))
        self.cancelButton_2.setText(_translate("teacherAppointmentWindow2", "CANCEL"))
        self.logoutButtonTeacher.setText(_translate("teacherAppointmentWindow2", "LOGOUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    teacherAppointmentWindow2 = QtWidgets.QDialog()
    ui = Ui_teacherAppointmentWindow2()
    ui.setupUi(teacherAppointmentWindow2)
    teacherAppointmentWindow2.show()
    sys.exit(app.exec_())
